{
    'name':'College Management',
    'description':'student,teacher info',
    'version':'17.0.1.0.0',
    'summary':'Student info',
    'category':'Education',
    'website':'erpharbor.in',
    'author':'Erp Harbor',
    'depends':['product',
    'sale',
    ],
    'data':[
    'data/sequence_data.xml',
    'security/ir.model.access.csv',
    'views/college_teacher_views.xml',
    'views/college_student_views.xml',
    'views/college_subject_views.xml',
    'views/college_exam_views.xml',
    'views/college_fees_views.xml',
    'views/college_sports_views.xml',
    'views/college_sportsform_views.xml',
    'views/product_attribute_views.xml',
    'views/sale_order_views.xml',
    'views/college_batsman_views.xml',
    'views/college_matches_views.xml',
    'views/college_players_views.xml',

    ],
    'lisence':'LGPL-3',
}  