from . import student
from . import teacher
from . import subject
from . import exam
from . import fees
from . import sports
from . import sportsform
from . import product_attribute
from . import sale_order
from . import batsman
from . import players
from . import ipl_scoreboard